"""
Runtime State Machine & States (Phase F).

Defines explicit, deterministic runtime states with strict transition logging.
"""

from enum import Enum


class RuntimeState(str, Enum):
    BOOTING = "BOOTING"
    PREMARKET_INITIALIZING = "PREMARKET_INITIALIZING"
    PREMARKET_READY = "PREMARKET_READY"
    WAITING_FOR_OPEN = "WAITING_FOR_OPEN"
    MARKET_OPEN = "MARKET_OPEN"
    TRADING_ACTIVE = "TRADING_ACTIVE"
    REDUCED_RISK = "REDUCED_RISK"
    CASH_PRESERVATION = "CASH_PRESERVATION"
    FLATTENING = "FLATTENING"
    POST_CLOSE_RECONCILIATION = "POST_CLOSE_RECONCILIATION"
    POST_CLOSE_JOURNAL = "POST_CLOSE_JOURNAL"
    SESSION_COMPLETE = "SESSION_COMPLETE"
    DEGRADED = "DEGRADED"
    HALTED = "HALTED"
